config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update ]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream
      else
        format.turbo_stream { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream
      else
        format.turbo_stream { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex w-2/3">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.erb
<%= form_with(model: post, class: "contents", remote: true, data: { controller: :post }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.erb
<div id="<%= dom_id post %>" class="text-lg" data-controller="posts" data-action="click->posts#show" data-url="<%= edit_post_path(post, format: :turbo_stream) %>">
  <h3 class="text-2xl mb-5 font-medium"><%= post.title %></h3>

  <p>
    <%= post.body %>
  </p>

</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.append :posts, partial: "post", locals: { post: @post } %>

app/views/posts/edit.turbo_stream.erb
<%= turbo_stream.update :post, partial: "form", locals: { post: @post } %>

app/views/posts/index.html.erb
<div class="w-full">
  <% content_for :title, "Posts" %>

  <div class="flex justify-between items-center my-20">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to "New post", "#", class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium", data: { controller: :posts, action: "click->posts#show", url: new_post_path(format: :turbo_stream) } %>
  </div>

  <div id="posts" class="min-w-full">
    <% @posts.each do |post| %>
      <%= turbo_frame_tag dom_id(post) do %>
        <%= render post %>
      <% end %>
    <% end %>
  </div>

  <div id="modal" class="flex justify-center items-center fixed top-0 left-0 w-full h-full hidden">
    <div class="absolute w-full h-screen bg-black bg-opacity-50" data-controller="posts" data-action="click->posts#close"></div>
    <div class="relative bg-white p-5 rounded-lg w-1/2">
      <%= turbo_frame_tag :post %>
    </div>
  </div>
</div>

app/views/posts/new.turbo_stream.erb
<%= turbo_stream.update :post, partial: "form", locals: { post: @post } %>

app/views/posts/show.html.erb
<%= turbo_frame_tag :post do %>
  <%= render @post %>
<% end %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@post), partial: "post", locals: { post: @post } %>
<%= turbo_stream.update :post, partial: "form", locals: { post: @post } %>